"""register_add_choice0.06

Revision ID: 0df97b0d7106
Revises: b40569b341ea
Create Date: 2021-03-15 11:03:07.828989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df97b0d7106'
down_revision = 'b40569b341ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isteacher', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isteacher')
    # ### end Alembic commands ###
